# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import agent_pb2 as agent__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in agent_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentServiceStub(object):
    """=============================================================================
    服务定义 (Service Definitions)
    =============================================================================

    Agent 服务
    提供用户消息处理、流式响应和健康检查功能
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessMessage = channel.unary_unary(
                '/agent.AgentService/ProcessMessage',
                request_serializer=agent__pb2.MessageRequest.SerializeToString,
                response_deserializer=agent__pb2.MessageResponse.FromString,
                _registered_method=True)
        self.StreamMessage = channel.unary_stream(
                '/agent.AgentService/StreamMessage',
                request_serializer=agent__pb2.MessageRequest.SerializeToString,
                response_deserializer=agent__pb2.StreamChunk.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/agent.AgentService/HealthCheck',
                request_serializer=agent__pb2.HealthRequest.SerializeToString,
                response_deserializer=agent__pb2.HealthResponse.FromString,
                _registered_method=True)


class AgentServiceServicer(object):
    """=============================================================================
    服务定义 (Service Definitions)
    =============================================================================

    Agent 服务
    提供用户消息处理、流式响应和健康检查功能
    """

    def ProcessMessage(self, request, context):
        """处理用户消息（同步模式）
        接收用户输入，返回完整的处理结果

        请求: MessageRequest - 包含会话ID、用户输入、模型ID等
        响应: MessageResponse - 包含答案、推理过程、执行历史等

        使用场景:
        - 非流式响应需求
        - 需要等待完整结果后统一返回
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamMessage(self, request, context):
        """流式处理用户消息（推荐）
        接收用户输入，以流式方式返回思考过程和生成内容

        请求: MessageRequest - 包含会话ID、用户输入、模型ID等
        响应: stream StreamChunk - 流式返回的数据块

        chunk_type 说明:
        - "thinking_start": 思考开始
        - "thinking_chunk": 思考内容块
        - "thinking_end": 思考结束
        - "answer_start": 答案开始
        - "answer": 答案内容块
        - "done": 完成
        - "error": 错误

        使用场景:
        - 需要实时展示思考过程
        - 需要实时展示生成内容
        - SSE 流式响应后端
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """健康检查
        检查 Agent 服务是否正常运行

        请求: HealthRequest - 空请求
        响应: HealthResponse - 服务状态信息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessMessage,
                    request_deserializer=agent__pb2.MessageRequest.FromString,
                    response_serializer=agent__pb2.MessageResponse.SerializeToString,
            ),
            'StreamMessage': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamMessage,
                    request_deserializer=agent__pb2.MessageRequest.FromString,
                    response_serializer=agent__pb2.StreamChunk.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=agent__pb2.HealthRequest.FromString,
                    response_serializer=agent__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agent.AgentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agent.AgentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentService(object):
    """=============================================================================
    服务定义 (Service Definitions)
    =============================================================================

    Agent 服务
    提供用户消息处理、流式响应和健康检查功能
    """

    @staticmethod
    def ProcessMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.AgentService/ProcessMessage',
            agent__pb2.MessageRequest.SerializeToString,
            agent__pb2.MessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/agent.AgentService/StreamMessage',
            agent__pb2.MessageRequest.SerializeToString,
            agent__pb2.StreamChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.AgentService/HealthCheck',
            agent__pb2.HealthRequest.SerializeToString,
            agent__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
